# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print("version",np.version)
print("config",np.show_config)

version <module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>
config <function show at 0x7fde005eac20>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [6]:
x=np.array([100,20,34])
a=x.size
print(a)
b=x.itemsize
print(b)
print("Memory size of numpy array in bytes:",a*b)

3
8
Memory size of numpy array in bytes: 24


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [8]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [9]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [11]:
v=np.arange(10,16)
print(v)
print("reverse vector:",v[::-1])

[10 11 12 13 14 15]
reverse vector: [15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [12]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [14]:
ar=np.array([1,2,0,0,4,0])
print(ar)
print(ar.nonzero())

[1 2 0 0 4 0]
(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [15]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [17]:
print(np.random.random((3,3,3)))

[[[0.9325881  0.58872157 0.28625114]
  [0.72195967 0.27566098 0.4748925 ]
  [0.50180761 0.83783991 0.00227889]]

 [[0.47680018 0.63097537 0.86724807]
  [0.53235649 0.45886356 0.40139901]
  [0.86869687 0.01720537 0.74587245]]

 [[0.10306346 0.00145729 0.36744122]
  [0.07972195 0.33200188 0.75156261]
  [0.06637015 0.22655209 0.86917871]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [18]:
x=np.random.random((10,10))
print("Minimum and Maximum values are ",x.min(),x.max())

Minimum and Maximum values are  0.004336693055111862 0.9970042000671515


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [20]:
x=np.random.random(30)
print(x.mean())
print(np.mean(x))

0.48087127645695615
0.48087127645695615


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [25]:
x=np.ones((4,4))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [31]:
x=np.ones((4,4))
print(np.pad(x, pad_width=1, mode='constant',constant_values=0))

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [148]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)
print(3*0.1)

nan
False
False
nan
False
0.30000000000000004


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [47]:
v= np.diag(1+np.arange(4),-1)
print(v)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [52]:
x=np.zeros((8,8))
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [53]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [67]:
x=np.array([[1,2],[3,4]])
x=np.tile(x,(4,4))
print(x)

[[1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [75]:
x=np.random.rand(5,5)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[0.         0.0270884  0.64568333 0.67237615 0.31562586]
 [0.27796571 0.30472626 0.87143959 0.30293813 0.14434372]
 [0.28162155 0.44223719 0.78550848 0.93952314 0.70393992]
 [0.78727142 0.98832337 0.70293282 1.         0.21715127]
 [0.48691658 0.38916648 0.18318742 0.47545952 0.68823252]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [76]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [80]:
x = np.dot(np.random.random((5,3)), np.ones((3,2)))
print(x)


[[1.85416142 1.85416142]
 [1.10353545 1.10353545]
 [1.47698093 1.47698093]
 [1.83109817 1.83109817]
 [1.89497762 1.89497762]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [82]:
x = np.arange(1,11)
x[(3 < x) & (x <= 8)] *= -1
print(x)

[ 1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [83]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [96]:
z=np.array([1,2,3])
print("original integer vector :",z)
print("z**z :",z**z)
print("2<<z>>2 :",2<<z>>2)
print("z<-z :",z<-z)
print("1j*z :",1j*z)
print("z/1/1 :",z/1/1)
#print("z<z>z :",z<z>z)--->not legal

original integer vector : [1 2 3]
z**z : [ 1  4 27]
2<<z>>2 : [1 2 4]
z<-z : [False False False]
1j*z : [0.+1.j 0.+2.j 0.+3.j]
z/1/1 : [1. 2. 3.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [98]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [109]:
x = np.random.uniform(-5,5,10)
print(x)
print(np.abs(x))
print(np.ceil(np.abs(x)))
print (np.copysign(np.ceil(np.abs(x)), x))

[ 1.14937852 -4.43599071 -0.09134784  3.95605546  2.89076267  4.82312929
 -0.79793838 -4.0932486  -1.77499842 -0.69647839]
[1.14937852 4.43599071 0.09134784 3.95605546 2.89076267 4.82312929
 0.79793838 4.0932486  1.77499842 0.69647839]
[2. 5. 1. 4. 3. 5. 1. 5. 2. 1.]
[ 2. -5. -1.  4.  3.  5. -1. -5. -2. -1.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [110]:
x=np.array([1,2,3,4])
y=np.array([2,4,6])
print(np.intersect1d(x,y))

[2 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [126]:
np.seterr(all="ignore")
np.ones(1)/0
print("Dead")
#np.seterr(all="warn")
#np.ones(1)/0
#print("back")

Dead
back


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [129]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [131]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Yesterday :",yesterday)
print("Today :",today)
print("Tomorrow :",tomorrow)

Yesterday : 2022-08-18
Today : 2022-08-19
Tomorrow : 2022-08-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [136]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [139]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
#print(A,B,C)
np.divide(A,2,out=A)
np.negative(A,out=A)
print(np.multiply(A,B,out=A))

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [142]:
Z = np.random.uniform(0,10,10)

print(Z)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[6.48719136 5.70293142 4.87753271 2.5679941  4.42583594 7.06829257
 6.21889235 4.50431922 2.4378607  6.65855913]
[6. 5. 4. 2. 4. 7. 6. 4. 2. 6.]
[6. 5. 4. 2. 4. 7. 6. 4. 2. 6.]
[6. 5. 4. 2. 4. 7. 6. 4. 2. 6.]
[6 5 4 2 4 7 6 4 2 6]
[6. 5. 4. 2. 4. 7. 6. 4. 2. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [144]:
x=np.zeros((5,5))
x+=np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [147]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=int,count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [149]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [154]:
x=np.random.random(10)
print(np.sort(x))

[0.00335756 0.02310085 0.1510136  0.16745841 0.31486706 0.3561451
 0.53221677 0.56836271 0.69886543 0.79090391]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [156]:
Z = np.arange(10)
print(Z)
np.add.reduce(Z)

[0 1 2 3 4 5 6 7 8 9]


45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [172]:
a=np.random.randint(0,5,10)
b=np.random.randint(0,5,10)

print(a)
print(b)
print("----------------")
print("allclose :",np.allclose(a,b))
print("array_equal:",np.array_equal(a,b))


[3 3 1 0 3 0 3 0 1 3]
[4 1 4 2 4 0 3 1 3 2]
----------------
allclose : False
array_equal: False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [174]:
x=np.ones(5)
x.flags.writeable = False
#x[2]=5

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [179]:
x=np.random.random(10)
print(x)
x[np.argmax(x)]=0
print(x)

[0.77232754 0.1990692  0.9075146  0.07411696 0.01229982 0.61581801
 0.94955845 0.31548899 0.6163808  0.78708888]
[0.77232754 0.1990692  0.9075146  0.07411696 0.01229982 0.61581801
 0.         0.31548899 0.6163808  0.78708888]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [188]:
a = np.ones((5,5), [('x',float),('y',float)])
a['x'],a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [191]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)
#print(np.linalg.det(C))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [195]:
for dtype in [np.int8, np.int32, np.int64]:
  print(dtype)
  print("Min:",np.iinfo(dtype).min,end=", ")
  print("Max :",np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(dtype)
  print("Min :",np.finfo(dtype).min,end=", ")
  print("Max :",np.finfo(dtype).max,end=", ")
  print("Eps :",np.finfo(dtype).eps)

<class 'numpy.int8'>
Min: -128, Max : 127
<class 'numpy.int32'>
Min: -2147483648, Max : 2147483647
<class 'numpy.int64'>
Min: -9223372036854775808, Max : 9223372036854775807
<class 'numpy.float32'>
Min : -3.4028235e+38, Max : 3.4028235e+38, Eps : 1.1920929e-07
<class 'numpy.float64'>
Min : -1.7976931348623157e+308, Max : 1.7976931348623157e+308, Eps : 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [199]:
Z = np.random.random((5,5))
print(Z)

[[0.17083919 0.67499936 0.16314796 0.14863868 0.00774051]
 [0.81195351 0.636977   0.15492306 0.9600668  0.48949716]
 [0.88463523 0.34261077 0.94653498 0.01391422 0.624381  ]
 [0.32335086 0.16836815 0.37960952 0.62581271 0.72659009]
 [0.53883537 0.03494555 0.39101071 0.53640399 0.2335586 ]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [200]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

30


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [201]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [203]:
x = np.arange(10, dtype=np.float32)
print(x)
x = x.astype(np.int32, copy=False)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
Z = np.genfromtxt("filename.txt", delimiter=",",dtype=int)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [204]:
x = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(x):
  print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [210]:
n = 5
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),5)
print(Z)

[[0. 5. 0. 0. 5.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [212]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(X)
print(Y)

[[0.85938618 0.87164545 0.39108118 0.33330437 0.01383608 0.05715687
  0.82213098 0.81778795 0.78268257 0.10338892]
 [0.65319406 0.60366299 0.57179846 0.90287715 0.41019037 0.15835651
  0.86723186 0.07376524 0.97104239 0.25388325]
 [0.13768252 0.53329586 0.84212996 0.27216228 0.19195464 0.54169585
  0.55795532 0.31227421 0.760425   0.15468984]
 [0.40042779 0.17986093 0.6766139  0.27256233 0.21985394 0.58021289
  0.46519953 0.97473546 0.76510901 0.78469667]
 [0.22138775 0.06004767 0.74198713 0.21102376 0.69320044 0.19772339
  0.58565913 0.85991435 0.76461486 0.6004122 ]]
[[ 0.35414612  0.3664054  -0.11415887 -0.17193569 -0.49140397 -0.44808318
   0.31689093  0.31254789  0.27744251 -0.40185114]
 [ 0.10659383  0.05706276  0.02519824  0.35627692 -0.13640986 -0.38824372
   0.32063164 -0.47283499  0.42444217 -0.29271698]
 [-0.29274403  0.10286931  0.41170341 -0.15826427 -0.23847191  0.1112693
   0.12752877 -0.11815233  0.32999845 -0.27573671]
 [-0.13149945 -0.35206631  0.14468666 -0.25936491 

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [214]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[4 4 8]
 [3 7 3]
 [5 0 7]]
[[5 0 7]
 [4 4 8]
 [3 7 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [223]:
#Z = np.random.randint(0,3,(3,10))
Z = np.array([1,0,4,2,3,4])
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [225]:
Z = np.random.uniform(0,10,10)
n = 5
m = Z.flat[np.abs(Z - n).argmin()]
print(m)

4.837387318039572


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [232]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
print(A,end="\n---------\n")
print(B,end="\n---------\n")
for x,y,z in it: 
  z[...] = x + y
print(it.operands[2])

[[0]
 [1]
 [2]]
---------
[[0 1 2]]
---------
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [234]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "My Array")
print (Z.name)

My Array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [236]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[2. 2. 3. 2. 3. 2. 2. 8. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [237]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [270]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[50 52 39 44]
 [45 48 75 54]
 [68 54 49 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [271]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
sum = np.bincount(S,weights=D)
count = np.bincount(S)
means = sum/count
print(means)

[0.54778149 0.34441234 0.59260748 0.35638074 0.59589713 0.58976017
 0.52594564 0.46135479 0.50895803 0.62675384]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [272]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
  
np.diag(np.dot(A, B))

array([1.35295127, 2.0603868 , 0.88115501, 2.25230315, 1.46021841])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [273]:
Z = np.array([1,2,3,4,5])
nz = 3
v = np.zeros(len(Z) + (len(Z)-1)*(nz))
v[::nz+1] = Z
print(v)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [274]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [275]:
A = np.arange(25).reshape(5,5)
print(A)
print("--------------------------")
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
--------------------------
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [277]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(np.bincount(A))

[0 2 1 1 2 0 1]
[0 2 1 1 2 0 1]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [278]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [282]:
Z = np.random.randint(0,2,100)
print(Z)
np.logical_not(Z, out=Z)
print(Z)
print("---------------------------------------------------------")
Z = np.random.uniform(-1.0,1.0,100)
print(Z)
np.negative(Z, out=Z)
print(Z)

[0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 0 0
 0 0 1 0 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 1 1 1 0 1 1 1 0 1 1 0 1 0 1 0 1 1 1
 1 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 1 0 1 0 1 0 1 0 0]
[1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 1 1
 1 1 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 1 0 0 0
 0 1 1 1 1 1 1 0 1 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 1]
---------------------------------------------------------
[-0.7834323  -0.10976188 -0.98477352  0.13792362  0.23912403  0.61294686
  0.63166869 -0.97174724  0.16342116 -0.63333743 -0.22633106  0.35571746
 -0.23907269  0.87336419 -0.49167143 -0.21635462 -0.72010279  0.42530356
 -0.80718377  0.93167277  0.38149206  0.85570147  0.89231996 -0.32402855
 -0.08579277 -0.4747112  -0.85038178  0.34586843 -0.17995995  0.5517304
  0.31868654 -0.44718845  0.07568594  0.33426308 -0.43416377 -0.15850777
  0.48982505  0.49529529  0.25798339  0.2578013  -0.96929209  0.31232814
 -0.82627024  0.40799643

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [295]:
import numpy.lib.stride_tricks as stride_tricks
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [287]:
Z = np.random.uniform(0,1,(10,15))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [293]:
z = np.random.randint(0,10,50)
print(z)
print(np.bincount(z).argmax())

[7 8 4 0 6 1 4 4 3 5 6 6 0 7 2 6 3 9 8 8 5 0 2 6 0 4 9 7 2 5 4 4 5 8 7 1 1
 9 7 8 9 6 2 9 3 3 9 4 5 4]
4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [296]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 2 0]
   [1 1 2]
   [1 4 1]]

  [[2 0 2]
   [1 2 1]
   [4 1 0]]

  [[0 2 4]
   [2 1 2]
   [1 0 4]]

  [[2 4 4]
   [1 2 0]
   [0 4 1]]

  [[4 4 1]
   [2 0 2]
   [4 1 1]]

  [[4 1 3]
   [0 2 0]
   [1 1 0]]

  [[1 3 4]
   [2 0 4]
   [1 0 0]]

  [[3 4 2]
   [0 4 0]
   [0 0 3]]]


 [[[1 1 2]
   [1 4 1]
   [2 1 4]]

  [[1 2 1]
   [4 1 0]
   [1 4 0]]

  [[2 1 2]
   [1 0 4]
   [4 0 3]]

  [[1 2 0]
   [0 4 1]
   [0 3 1]]

  [[2 0 2]
   [4 1 1]
   [3 1 0]]

  [[0 2 0]
   [1 1 0]
   [1 0 4]]

  [[2 0 4]
   [1 0 0]
   [0 4 4]]

  [[0 4 0]
   [0 0 3]
   [4 4 3]]]


 [[[1 4 1]
   [2 1 4]
   [4 0 3]]

  [[4 1 0]
   [1 4 0]
   [0 3 3]]

  [[1 0 4]
   [4 0 3]
   [3 3 0]]

  [[0 4 1]
   [0 3 1]
   [3 0 0]]

  [[4 1 1]
   [3 1 0]
   [0 0 0]]

  [[1 1 0]
   [1 0 4]
   [0 0 3]]

  [[1 0 0]
   [0 4 4]
   [0 3 0]]

  [[0 0 3]
   [4 4 3]
   [3 0 0]]]


 [[[2 1 4]
   [4 0 3]
   [3 2 2]]

  [[1 4 0]
   [0 3 3]
   [2 2 0]]

  [[4 0 3]
   [3 3 0]
   [2 0 4]]

  [[0 3 1]
   [3 0 0]
   [0 4 3]]

  [[3 1 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [297]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [298]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [299]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9995 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [300]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [301]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [305]:
x = np.random.rand(5**7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

6 ms ± 99.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
150 µs ± 1.22 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
164 µs ± 951 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [269]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [268]:
Z = np.random.randint(0,5,(10,3))
print(Z,end="\n------------\n")
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 0 3]
 [4 1 4]
 [3 3 1]
 [1 4 2]
 [4 0 3]
 [3 4 2]
 [2 1 4]
 [4 0 0]
 [3 4 0]
 [0 4 1]]
------------
[[1 0 3]
 [4 1 4]
 [3 3 1]
 [1 4 2]
 [4 0 3]
 [3 4 2]
 [2 1 4]
 [4 0 0]
 [3 4 0]
 [0 4 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [262]:
I = np.array([0, 1, 2, 3, 5, 16, 32, 64, 25], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [259]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
u = Z[idx]
print(u)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [255]:
A = np.random.uniform(0,5,10)
B = np.random.uniform(0,5,10)
print("A:\n",A)
print("B:\n",B)
print("-----------")
print(np.einsum('i->', A),end="\n------\n" )      # np.sum(A)
print(np.einsum('i,i->i', A, B),end="\n------\n" ) # A * B
print(np.einsum('i,i', A, B),end="\n------\n" )    # np.inner(A, B)
print(np.einsum('i,j->ij', A, B),end="\n------\n" )    # np.outer(A, B)

A:
 [4.29659467 4.82815568 2.63191757 4.92205358 4.99887269 0.37973549
 1.61950343 0.37429746 1.04929309 0.15004637]
B:
 [3.19215654 3.47673459 0.38069598 2.00455785 0.84649686 3.50523249
 3.15654033 3.90292356 3.64391829 2.91908237]
-----------
25.250470038575493
------
[13.7154028  16.78621587  1.00196044  9.86654116  4.23153005  1.33106118
  5.11202789  1.46085438  3.82353829  0.43799772]
------
57.76712977377342
------
[[13.7154028  14.93811934  1.63569631  8.6127726   3.63705391 15.06056325
  13.56237437 16.76928056 15.65643993 12.54211377]
 [15.41222874 16.78621587  1.83805945  9.67831738  4.08701863 16.92380815
  15.24026811 18.84392252 17.5934048  14.09378413]
 [ 8.4014929   9.15047887  1.00196044  5.27583104  2.22790997  9.22548298
   8.30775396 10.27217308  9.59049259  7.68278419]
 [15.71196554 17.11267396  1.87380601  9.86654116  4.16650291 17.25294213
  15.53666063 19.21039886 17.93556109 14.36787984]
 [15.95718417 17.37975362  1.90305073 10.02052951  4.23153005 17.52221097

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [249]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [245]:
X = np.random.randn(100)
#print(x)
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
#print(idx)
means = X[idx].mean(axis=1)
#print(means)
per = np.percentile(means, [2.5, 97.5])
print(per)

[-0.22104333  0.16524766]
